version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ec2-user

  # 로드밸런서 트래픽 처리용
  # BeforeAllowTraffic:
  #   - location: scripts/before-traffic.sh
  #     timeout: 60
  #     runas: ec2-user

  # AllowTraffic:
  #   - location: scripts/allow-traffic.sh
  #     timeout: 60
  #     runas: ec2-user

  # AfterAllowTraffic:
  #   - location: scripts/after-traffic.sh
  #     timeout: 60
  #     runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ec2-user
