version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "[INSTALL] 의존성 설치 시작"
      - cd Web/webapp
      - yarn install

  pre_build:
    commands:
      - echo "NEXT_PUBLIC_SPORTS_API_KEY=202f212e49d55e7bc005f7225c10cfec" >> .env
      - echo "NEXT_PUBLIC_BACKEND_API_ENDPOINT=https://www.1bean.shop" >> .env
      - echo "NEXT_PUBLIC_SOCKET_SERVER_ENDPOINT=wss://www.1bean.shop" >> .env
      - echo "PORT=3000" >> .env
      - echo "NODE_ENV=development" >> .env

  build:
    commands:
      - echo "[BUILD] Next.js 빌드 시작"
      - sleep 30
      - yarn build

  post_build:
    commands:
      - echo "[POST-BUILD] 결과물 압축 준비"
      - mkdir -p $CODEBUILD_SRC_DIR/deploy-output
      - cp -r .next $CODEBUILD_SRC_DIR/deploy-output/
      - cp -r public $CODEBUILD_SRC_DIR/deploy-output/
      - cp package.json $CODEBUILD_SRC_DIR/deploy-output/
      - cp yarn.lock $CODEBUILD_SRC_DIR/deploy-output/
      - cp next.config.mjs $CODEBUILD_SRC_DIR/deploy-output/
      - cp appspec.yml $CODEBUILD_SRC_DIR/deploy-output/
      - chmod +x scripts/*.sh
      - cp -r scripts $CODEBUILD_SRC_DIR/deploy-output/

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/deploy-output
