#!/bin/bash

# MySQL 명령어 실행
mysql -h "$DB_ENDPOINT" -u "$DB_USERNAME" -p"$DB_PASSWORD" <<EOT
CREATE DATABASE IF NOT EXISTS userDB;
CREATE DATABASE IF NOT EXISTS gameDB;

#Table생성
USE userDB;
DROP TABLE IF EXISTS userTBL;
CREATE TABLE userTBL ( 
    id VARCHAR(10) NOT NULL PRIMARY KEY,
    nickname VARCHAR(30) NOT NULL,
    password CHAR(60) NOT NULL,
    e_mail VARCHAR(320) NOT NULL UNIQUE, 
    phone_number VARCHAR(10) NOT NULL, 
    balance BIGINT DEFAULT 0,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

USE gameDB;
DROP TABLE IF EXISTS gameinfoTBL;
CREATE TABLE gameinfoTBL ( 
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL, 
    gameDate DATETIME NOT NULL,
    home VARCHAR(20) NOT NULL,
    away VARCHAR(20) NOT NULL,
    wdl ENUM('WIN', 'DRAW', 'LOSE')  NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0, 
    status BOOLEAN DEFAULT TRUE
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    PRIMARY KEY (id, gametypeDate)
);

DROP TABLE IF EXISTS gameresultTBL;
CREATE TABLE gameresultTBL ( 
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL, 
    gameDate DATETIME NOT NULL,
    home VARCHAR(20) NOT NULL,
    away VARCHAR(20) NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0, 
    result ENUM('WIN', 'DRAW', 'LOSE')  NOT NULL,
    resultPrice BIGINT DEFAULT 0,
    PRIMARY KEY (id, type), 
    FOREIGN KEY (id, type) REFERENCES gameinfoTBL(id, type) ON DELETE CASCADE
);

EOT