#!/bin/bash

# MySQL 명령어 실행
mysql -h "$DB_ENDPOINT" -u "$DB_USERNAME" -p"$DB_PASSWORD" <<EOT
CREATE DATABASE IF NOT EXISTS userDB;
CREATE DATABASE IF NOT EXISTS gameDB;
CREATE DATABASE IF NOT EXISTS chatDB;

#Table생성
USE userDB;
CREATE TABLE IF NOT EXISTS userTBL ( 
    id VARCHAR(10) NOT NULL PRIMARY KEY,
    nickname VARCHAR(30) NOT NULL,
    password CHAR(60) NOT NULL,
    e_mail VARCHAR(320) NOT NULL UNIQUE, 
    phone_number VARCHAR(10) NOT NULL, 
    balance BIGINT DEFAULT 0,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

USE gameDB;
CREATE TABLE IF NOT EXISTS gameinfoTBL ( 
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL,
    matchid VARCHAR(8) NOT NULL,
    gameDate DATETIME NOT NULL,
    home VARCHAR(20) NOT NULL,
    away VARCHAR(20) NOT NULL,
    wdl ENUM('HOME', 'DRAW', 'AWAY')  NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0 NOT NULL, 
    status ENUM ('BEFORE', 'PLAYING', 'FINISHED') NOT NULL,
    modified_date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id, matchid)
);

CREATE TABLE IF NOT EXISTS gameresultTBL ( 
    id VARCHAR(10) NOT NULL,
    type ENUM('FOOTBALL', 'BASEBALL', 'BASKETBALL', 'ICEHOCKEY', 'HANDBALL') NOT NULL, 
    matchid VARCHAR(8) NOT NULL,
    gameDate DATETIME NOT NULL,
    home VARCHAR(20) NOT NULL,
    away VARCHAR(20) NOT NULL,
    odds DECIMAL(5,2) NOT NULL,
    price BIGINT DEFAULT 0, 
    result ENUM('WIN', 'LOSE')  NOT NULL,
    resultPrice BIGINT DEFAULT 0,
    PRIMARY KEY (id, matchid),
    FOREIGN KEY (id, matchid) REFERENCES gameinfoTBL(id, matchid) ON DELETE CASCADE
);

USE chatDB;

EOT